Add API support example for modified Dockerfile
bitnami/bitnami-docker-suitecrm pull request #125
Opened 2021-01-11 17:48 UTC by sutidor

**Description of the change**

Add API support example for modified Dockerfile

**Benefits**

Searching and debugging "whats wrong with API, because it used to work without modification on older images" be gone.

**Possible drawbacks**

None, as it is only change in readme

2021-01-13 10:43 UTC, marcosbc requested changes
Thanks for the contribution!

I've added a few comments regarding these changes. I'm also wondering about this:

> whats wrong with API, because it used to work without modification on older images

Note that older images did not include the public.key/private.key files (i.e. you can see this in `bitnami/suitecrm:7.11.18-debian-10-r11`), are you sure that used to work before?

2021-01-13 10:43 UTC, marcosbc commented on README.md
> +sed -i "s/AllowOverride None/AllowOverride All/g" /opt/bitnami/apache2/conf/vhosts/suitecrm-https-vhost.conf &&
I don't think we'd need to add `AllowOverride All` as the `.htaccess` file is moved to `/opt/bitnami/apache/conf/vhosts/htaccess/suitecrm-htaccess.conf`:

```console
$ cat /opt/bitnami/suitecrm/lib/API/OAuth2/.htaccess
# This configuration has been moved to the /opt/bitnami/apache/conf/vhosts/htaccess/suitecrm-htaccess.conf config file for performance and security reasons
```

2021-01-13 10:43 UTC, marcosbc commented on README.md
> +USER 0 # Required to perform privileged actions
There is no need to run these actions as user 0 / root if we're not configuring `suitecrm-vhost.conf`/`suitecrm-https-vhost.conf`. Also the `chown daemon:daemon` should not be needed by default since this is a non-root container.

2021-01-13 14:44 UTC, sutidor commented on README.md
> +sed -i "s/AllowOverride None/AllowOverride All/g" /opt/bitnami/apache2/conf/vhosts/suitecrm-https-vhost.conf &&
The `/conf/vhosts/htaccess/suitecrm-htaccess.conf` contains only
```
<Directory "/opt/bitnami/suitecrm/lib/API/OAuth2">
  RedirectMatch 403 (?i).*\.key$
</Directory>
```
What I need is the .htaccess file in
`/opt/bitnami/suitecrm/.htaccess` specifically
```
RewriteRule ^Api/(.*)$ - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteRule ^Api/access_token$ Api/index.php [L]
RewriteRule ^Api/V8/(.*?)$ Api/index.php [L]
```

AllowOverride mod_rewrite would be sufficient though

2021-01-14 15:43 UTC, marcosbc commented on README.md
> +sed -i "s/AllowOverride None/AllowOverride All/g" /opt/bitnami/apache2/conf/vhosts/suitecrm-https-vhost.conf &&
I see. In that case there is actually a bug in the container as it should not use `AllowOverride None` at all. Could you make this change instead?

```diff
diff --git a/7/debian-10/rootfs/opt/bitnami/scripts/suitecrm/postunpack.sh b/7/debian-10/rootfs/opt/bitnami/scripts/suitecrm/postunpack.sh
index f0f1ee4..325f632 100755
--- a/7/debian-10/rootfs/opt/bitnami/scripts/suitecrm/postunpack.sh
+++ b/7/debian-10/rootfs/opt/bitnami/scripts/suitecrm/postunpack.sh
@@ -44,4 +44,5 @@ php_conf_set "opcache.enable" "Off"
 # Enable default web server configuration for SuiteCRM
 info "Creating default web server configuration for SuiteCRM"
 web_server_validate
-ensure_web_server_app_configuration_exists "suitecrm" --type php
+# Not moving .htaccess because SuiteCRM generates some of them during installation
+ensure_web_server_app_configuration_exists "suitecrm" --type php --apache-move-htaccess "no"
```

2021-01-14 15:47 UTC, marcosbc reviewed
A couple of small requests, after this it should be fine to merge. Thanks!

2021-01-14 15:47 UTC, marcosbc commented on README.md
> +sed -i "s/AllowOverride None/AllowOverride mod_rewrite/g" /opt/bitnami/apache2/conf/vhosts/suitecrm-https-vhost.conf &&
With the changes I mentioned previously (affecting postunpack.sh), these lines would no longer be needed and would be enough just to generate the appropriate cert files.

AFAIK it would have been the same with older images as they were not included at that point, so this would be valid for both old and new images.

I'm still a bit confused respect to your mention that this worked without issues before, did you mean that these files were already created in older images? Or was this change necessary anyways?

2021-01-15 19:05 UTC, sutidor commented on README.md
> +sed -i "s/AllowOverride None/AllowOverride mod_rewrite/g" /opt/bitnami/apache2/conf/vhosts/suitecrm-https-vhost.conf &&
sorry I didn't answer to that question:
I had to generate keys before, but from there the API worked (as far as I recall anyways...)  ->without enabling any .htaccess

2021-01-15 19:16 UTC, sutidor commented on README.md
> +sed -i "s/AllowOverride None/AllowOverride All/g" /opt/bitnami/apache2/conf/vhosts/suitecrm-https-vhost.conf &&
Suitecrm has an admin function to (re-)generate .htaccess for various reasons. I know that certain plugins introduce changes to .htaccess. Example: If you enable the mautic integration to suitecrm there are additional .htaccess rules to route the API calls correctly to non-standard endpoints.

Do I understand correctly that this solution will be using the original .htaccess - even if it is modified in an existing container?

2021-01-18 08:49 UTC, marcosbc approved these changes
Awesome, thank you!

2021-01-18 08:58 UTC, merged

2021-01-18 08:59 UTC, marcosbc commented on README.md
> +sed -i "s/AllowOverride None/AllowOverride All/g" /opt/bitnami/apache2/conf/vhosts/suitecrm-https-vhost.conf &&
Yes, this change will ensure that the original .htaccess is left and be used, allowing the app to update it accordingly during the wizard and also setting "AllowOverride all" into Apache's settings for SuiteCRM.